title: jaxions
description: Axion field evolution around the QCD phase transition
theme: just-the-docs
baseurl: "/docs" 
url: "https://veintemillas.github.io/jaxions" 
repository: veintemillas/jaxions 
